type skillType = {
    type: 'FE' | 'BE' | 'DB' | 'DO' | 'PL' | 'etc' | 'OS';
    name: string;
    image: string;
    comment: string;
    highlight: boolean;
}

export const skills: Array<skillType> = [
    {
        type: 'FE',
        name: 'HTML',
        image: 'html',
        comment: "I follow the semantic markup and have experience of SEO. I can support various platforms and browsers. I have learned HTML since 2006 when I made the first website with Macromedia Flash and iframe.",
        highlight: true,
    },
    {
        type: 'FE',
        name: 'CSS',
        image: 'css',
        comment: "I am used to using Flexbox and can use CSS preprocessor.",
        highlight: true,
    },
    {
        type: 'FE',
        name: 'React.js',
        image: 'react',
        comment: "I enjoy using React Hooks. I can divide components by reasonable way and modularize with some common logics.",
        highlight: true,
    },
    {
        type: 'FE',
        name: 'Next.js',
        image: 'next',
        comment: "I know what to do to achieve SEO in Next.js SSR Application.",
        highlight: true,
    },
    {
        type: 'FE',
        name: 'Angular.js',
        image: 'angular',
        comment: "I know how the components are managed and rendered, and how to make services.",
        highlight: false,
    },
    {
        type: 'FE',
        name: 'jQuery',
        image: 'jquery',
        comment: "I can use basic jQuery library.",
        highlight: false,
    },
    {
        type: 'FE',
        name: 'Redux',
        image: 'redux',
        comment: "I follow Ducks pattern in Redux.",
        highlight: false,
    },
    {
        type: 'FE',
        name: 'MobX',
        image: 'mobx',
        comment: "I do basic state management.",
        highlight: false,
    },
    {
        type: 'FE',
        name: 'React Native',
        image: 'rn',
        comment: "I have published full-stack mobile applications on both Apple App Store and Google Play.",
        highlight: true,
    },
    {
        type: 'BE',
        name: 'Node.js',
        image: 'node',
        comment: "I am used to building a REST API back-end server based on Express.js.",
        highlight: true,
    },
    {
        type: 'BE',
        name: 'Java Spring',
        image: 'spring',
        comment: "I can set the development environment and build a back-end server.",
        highlight: false,
    },
    {
        type: 'BE',
        name: 'GraphQL',
        image: 'graphql',
        comment: "I studied basic GraphQL with Apollo.",
        highlight: false,
    },
    {
        type: 'DB',
        name: 'MySQL',
        image: 'mysql',
        comment: "I have a Bachelor's knowledge of the database and am familiar with writing multiple subqueries.",
        highlight: true,
    },
    {
        type: 'DB',
        name: 'Oracle',
        image: 'oracle',
        comment: "I have a Bachelor's knowledge of the database and am familiar with writing multiple subqueries.",
        highlight: true,
    },
    {
        type: 'DB',
        name: 'MongoDB',
        image: 'mongodb',
        comment: "I know the pros and cons of NoSQL and how to use MongoDB and mongoose.",
        highlight: true,
    },
    {
        type: 'DO',
        name: 'AWS',
        image: 'aws',
        comment: "I have some experience using AWS EC2, S3, Route53, CloudFront, RDS, Elastic Beanstalk.",
        highlight: true,
    },
    {
        type: 'DO',
        name: 'Git',
        image: 'Git',
        comment: "I know the basics of configuration management.",
        highlight: true,
    },
    {
        type: 'DO',
        name: 'Docker',
        image: 'docker',
        comment: "I know what is image and container in Docker, and have read about Docker Compose.",
        highlight: false,
    },
    {
        type: 'DO',
        name: 'Jest',
        image: 'jest',
        comment: "I know importance of TDD and have tried Jest and Enzyme once.",
        highlight: false,
    },
    // {
    //     type: 'DO',
    //     name: 'Enzyme',
    //     image: 'enzyme',
    //     comment: "",
    //     highlight: false,
    // },
    // {
    //     type: 'DO',
    //     name: 'Jenkins',
    //     image: 'jenkins',
    //     comment: "",
    //     highlight: false,
    // },
    {
        type: 'DO',
        name: 'Vercel',
        image: 'vercel',
        comment: "I have deployed Next.js applications.",
        highlight: true,
    },
    {
        type: 'DO',
        name: 'Heroku',
        image: 'heroku',
        comment: "I have deployed React.js, Angular.js, Node.js applications.",
        highlight: true,
    },
    {
        type: 'PL',
        name: 'Javascript',
        image: 'javascript',
        comment: "I am familiar with ES6 or above, and use appropriate data structures depending on the situation.",
        highlight: true,
    },
    {
        type: 'PL',
        name: 'Typescript',
        image: 'typescript',
        comment: "I know the importance of type writing and try to use Typescript whenever I can.",
        highlight: true,
    },
    {
        type: 'PL',
        name: 'Java',
        image: 'java',
        comment: "I have a Bachelor's knowledge of Java language and OOP.",
        highlight: false,
    },
    {
        type: 'PL',
        name: 'C/C++',
        image: 'c',
        comment: "I have a Bachelor's knowledge of C/C++ language and know how to use STL.",
        highlight: false,
    },
    {
        type: 'etc',
        name: 'Yarn',
        image: 'yarn',
        comment: "",
        highlight: true,
    },
    {
        type: 'etc',
        name: 'npm',
        image: 'npm',
        comment: "",
        highlight: true,
    },
    {
        type: 'etc',
        name: 'webpack',
        image: 'webpack',
        comment: "I can set up an environment that meets the requirements of the project.",
        highlight: false,
    },
    {
        type: 'etc',
        name: 'Adobe Photoshop',
        image: 'photoshop',
        comment: "I have been using Photoshop for more than 10 years since version 7.0.",
        highlight: true,
    },
    {
        type: 'etc',
        name: 'Adobe Illustrator',
        image: 'illustrator',
        comment: "I know the basic usage.",
        highlight: false,
    },
    {
        type: 'etc',
        name: 'Adobe Premiere Pro / After Effect',
        image: 'premiere',
        comment: "I know the basic usage of them.",
        highlight: false,
    },
    {
        type: 'OS',
        name: 'Windows',
        image: 'windows',
        comment: "I am using Dell XPS 9560 and used to have a custom-built PC.",
        highlight: true,
    },
    {
        type: 'OS',
        name: 'Mac OS',
        image: 'mac',
        comment: "I am using MacBook Pro 2019 Touch Bar.",
        highlight: true,
    },
    {
        type: 'OS',
        name: 'Linux(Ubuntu)',
        image: 'ubuntu',
        comment: "I have installed Ubuntu in AWS EC2 and Raspberry Pi before.",
        highlight: true,
    },
]